library(tidyverse)
library(broom)
library(rgdal)
library(sp)
df_raw <- read_csv("data/immo_data.csv")

# Nicht benotigte Spalte entfernen
df_clean_cols <- subset(df_raw, select = -c(
telekomTvOffer
,telekomHybridUploadSpeed
,newlyConst
,picturecount
,pricetrend
,telekomUploadSpeed
,scoutId
,noParkSpaces
,firingTypes
,yearConstructedRange
,houseNumber
,condition
,interiorQual
,petsAllowed
,street
,streetPlain
,baseRentRange
,thermalChar
,numberOfFloors
,noRoomsRange
,livingSpaceRange
,description
,facilities
,heatingCosts
,energyEfficiencyClass
,lastRefurbish
,electricityBasePrice
,electricityKwhPrice
,totalRent
,geo_bln
,geo_krs
,regio3
,date
))

#drop raw
rm(list = c("df_raw"))
### Bereinigung von Datensaetzen
df_clean_na <- na.omit(df_clean_cols) # NAs

write.csv2(df_clean_na, file = "data/immo_scout_cleaned_cols_no_na.csv",row.names = FALSE) # Zwischenspeichern

df_clean_1 <- subset(df_clean_na, floor < 64) # Hoechste Gebaude in DE hat 63 Stockwerke
df_clean_2 <- subset(df_clean_1, noRooms > 0) # Es muss mindesten ein Zimmer vorhanden sein
df_clean_3 <- subset(df_clean_2, livingSpace > 0) # Wohnflaeche muss gueltig sein
df_clean_4 <- subset(df_clean_3, yearConstructed > 1214) # Das aelteste Haus in DE ist 1215
df_clean_4 <- subset(df_clean_4, yearConstructed < 2021) # Erhebung war in 2018 und 2019. Vielleicht wurden Wohnung angeboten die in 2020 fertigstellt werden
df_clean_5 <- subset(df_clean_4, baseRent > 0) # Miete muss groesser 0 sein
df_clean_5 <- subset(df_clean_5, baseRent != 999) # unplasible Werte
df_clean_5 <- subset(df_clean_5, baseRent != 9999) # unplasible Werte
df_clean_5 <- subset(df_clean_5, baseRent != 99999) # unplasible Werte
df_clean_5 <- subset(df_clean_5, baseRent != 120000) # unplasible Werte
df_clean_5 <- subset(df_clean_5, baseRent != 30990) # unplasible Werte
df_clean_6 <- subset(df_clean_5, serviceCharge > 0) # Nebenkosten muessen groeßer sein
df_clean_7 <- subset(df_clean_6, serviceCharge != baseRent) # Nebenkosten und Miete duerfen nicht gleich sein
# Unterstriche durch Leerzeichen ersetzen
df_clean_8 <- df_clean_7
df_clean_8$regio1 <- str_replace_all(df_clean_8$regio1,"_","-")
df_clean_8$regio2 <- str_replace_all(df_clean_8$regio2,"_","-")
df_clean_8$heatingType <- str_replace_all(df_clean_8$heatingType,"_"," ")
df_clean_8$typeOfFlat <- str_replace_all(df_clean_8$typeOfFlat,"_"," ")
# Spalten uebersetzen: Heizungsart
df_clean_9 <- df_clean_8
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"self contained central heating","autonome Zentralheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"central heating","Zentralheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"floor heating","Fußbodenheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"district heating","Fernwärme")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"oil heating","Ölheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"gas heating","Gasheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"electric heating","elektrische Heizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"combined heat and power plant","Kraft-Wärme-Kopplungsanlage")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"heat pump","Wärmepumpe")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"night storage heater","Nachtspeicherheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"wood pellet heating","Holzpellet-Heizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"stove heating","Ofenheizung")
df_clean_9$heatingType <- str_replace_all(df_clean_9$heatingType,"solar heating","Solarheizung")
# Spalten uebersetzen: Wohnungstyp
df_clean_10 <- df_clean_9
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"raised ground floor","Hochparterre")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"ground floor","Erdgeschoss")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"apartment","Wohnung")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"other","sonstige")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"roof storey","Dachgeschoss")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"terraced flat","Terrassenwohnung")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"maisonette","Maisonette")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"penthouse","Penthouse")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"half basement","Souterrain")
df_clean_10$typeOfFlat <- str_replace_all(df_clean_10$typeOfFlat,"loft","Loft")
# Landkreise bereinigen
df_clean_11 <- df_clean_10
# ACHTUNG BIS HIER HER AUSUEHREN UND DANN das landkreise_cleaning.R ausfuehren und dann weiter
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aachen-Kreis","Städteregion Abachen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aachen","Städteregion Aachen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Städteregion Abachen","Städteregion Aachen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ahrweiler-Kreis","Ahrweiler")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aichach-Friedberg-Kreis","Aichach-Friedberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Alb-Donau-Kreis","Alb-Donau-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Altenburger-Land-Kreis","Altenburger Land")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Altenkirchen-Westerwald-Kreis","Altenkirchen (Westerwald)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Altmarkkreis-Salzwedel","Altmarkkreis Salzwedel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Altötting-Kreis","Altötting")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Alzey-Worms-Kreis","Alzey-Worms")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Amberg-Sulzbach-Kreis","Amberg-Sulzbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Amberg","Amberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ammerland-Kreis","Ammerland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Anhalt-Bitterfeld-Kreis","Anhalt-Bitterfeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ansbach-Kreis","Ansbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ansbach","Ansbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aschaffenburg-Kreis","Aschaffenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aschaffenburg","Aschaffenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Augsburg-Kreis","Augsburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Augsburg","Augsburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Aurich-Kreis","Aurich")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bad-Doberan-Kreis","Rostock")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bad-Dürkheim-Kreis","Bad Dürkheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bad-Kissingen-Kreis","Bad Kissingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bad-Kreuznach-Kreis","Bad Kreuznach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bad-Tölz-Wolfratshausen-Kreis","Bad Tölz-Wolfratshausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Baden-Baden","Baden-Baden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bamberg-Kreis","Bamberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bamberg","Bamberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Barnim-Kreis","Barnim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bautzen-Kreis","Bautzen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bayreuth-Kreis","Bayreuth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bayreuth","Bayreuth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Berchtesgadener-Land-Kreis","Berchtesgadener Land")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bergstraße-Kreis","Bergstraße")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Berlin","Berlin")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bernkastel-Wittlich-Kreis","Bernkastel-Wittlich")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Biberach-Kreis","Biberach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bielefeld","Bielefeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Birkenfeld-Kreis","Birkenfeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bitburg-Prüm-Kreis","Eifelkreis Bitburg-Prüm")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Böblingen-Kreis","Böblingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bochum","Bochum")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bodenseekreis","Bodenseekreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bonn","Bonn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Börde-Kreis","Börde")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Borken-Kreis","Borken")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bottrop","Bottrop")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Brandenburg-an-der-Havel","Brandenburg an der Havel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Braunschweig","Braunschweig")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Breisgau-Hochschwarzwald-Kreis","Breisgau-Hochschwarzwald")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bremerhaven","Bremerhaven")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Bremen","Bremen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Burgenlandkreis","Burgenlandkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Calw-Kreis","Calw")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Celle-Kreis","Celle")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Cham-Kreis","Cham")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Chemnitz","Chemnitz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Cloppenburg-Kreis","Cloppenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Coburg-Kreis","Coburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Coburg","Coburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Cochem-Zell-Kreis","Cochem-Zell")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Coesfeld-Kreis","Coesfeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Cottbus","Cottbus")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Cuxhaven-Kreis","Cuxhaven")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dachau-Kreis","Dachau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dahme-Spreewald-Kreis","Dahme-Spreewald")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Darmstadt","Darmstadt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Darmstadt-Dieburg-Kreis","Darmstadt-Dieburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Deggendorf-Kreis","Deggendorf")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Delmenhorst","Delmenhorst")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Demmin-Kreis","Mecklenburgische Seenplatte")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dessau-Roßlau","Dessau-Roßlau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Diepholz-Kreis","Diepholz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dillingen-an-der-Donau-Kreis","Dillingen a.d. Donau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dingolfing-Landau-Kreis","Dingolfing-Landau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dithmarschen-Kreis","Dithmarschen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Donau-Ries-Kreis","Donau-Ries")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Donnersbergkreis","Donnersbergkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dortmund","Dortmund")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Dresden","Dresden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Duisburg","Duisburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Düren-Kreis","Düren")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Düsseldorf","Düsseldorf")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ebersberg-Kreis","Ebersberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Eichsfeld-Kreis","Eichsfeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Eichstätt-Kreis","Eichstätt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Eisenach","Eisenach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Elbe-Elster-Kreis","Elbe-Elster")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Emden","Emden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Emmendingen-Kreis","Emmendingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Emsland-Kreis","Emsland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ennepe-Ruhr-Kreis","Ennepe-Ruhr-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Enzkreis","Enzkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Erding-Kreis","Erding")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Erfurt","Erfurt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Erlangen-Höchstadt-Kreis","Erlangen-Höchstadt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Erlangen","Erlangen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Erzgebirgskreis","Erzgebirgskreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Essen","Essen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Esslingen-Kreis","Esslingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Euskirchen-Kreis","Euskirchen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Flensburg","Flensburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Forchheim-Kreis","Forchheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Frankenthal-Pfalz","Frankenthal (Pfalz)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Frankfurt-am-Main","Frankfurt am Main")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Frankfurt-Oder","Frankfurt (Oder)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Freiburg-im-Breisgau","Freiburg im Breisgau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Freising-Kreis","Freising")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Freudenstadt-Kreis","Freudenstadt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Freyung-Grafenau-Kreis","Freyung-Grafenau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Friesland-Kreis","Friesland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Fulda-Kreis","Fulda")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Fürstenfeldbruck-Kreis","Fürstenfeldbruck")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Fürth-Kreis","Fürth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Fürth","Fürth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Garmisch-Partenkirchen-Kreis","Garmisch-Partenkirchen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gelsenkirchen","Gelsenkirchen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gera","Gera")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Germersheim-Kreis","Germersheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gießen-Kreis","Gießen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gifhorn-Kreis","Gifhorn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Göppingen-Kreis","Göppingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Görlitz-Kreis","Görlitz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Görlitz","Görlitz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Goslar-Kreis","Goslar")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gotha-Kreis","Gotha")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Göttingen-Kreis","Göttingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Grafschaft-Bentheim-Kreis","Grafschaft Bentheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Greifswald","Vorpommern-Greifswald")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Greiz-Kreis","Greiz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Groß-Gerau-Kreis","Groß-Gerau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Günzburg-Kreis","Günzburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Güstrow-Kreis","Rostock")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Gütersloh-Kreis","Gütersloh")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hagen","Hagen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Halle-Saale","Halle (Saale)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hamburg","Hamburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hameln-Pyrmont-Kreis","Hameln-Pyrmont")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hamm","Hamm")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hannover-Kreis","Region Hbannover")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hannover","Region Hannover")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Region Hbannover","Region Hannover")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Harburg-Kreis","Harburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Harz-Kreis","Harz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Haßberge-Kreis","Haßberge")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Havelland-Kreis","Havelland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heidekreis","Heidekreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heidelberg","Heidelberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heidenheim-Kreis","Heidenheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heilbronn-Kreis","Heilbronn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heilbronn","Heilbronn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Heinsberg-Kreis","Heinsberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Helmstedt-Kreis","Helmstedt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Herford-Kreis","Herford")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Herne","Herne")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hersfeld-Rotenburg-Kreis","Hersfeld-Rotenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Herzogtum-Lauenburg-Kreis","Herzogtum Lauenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hildburghausen-Kreis","Hildburghausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hildesheim-Kreis","Hildesheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hochsauerlandkreis","Hochsauerlandkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hochtaunuskreis","Hochtaunuskreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hof-Kreis","Hof")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hof","Hof")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hohenlohekreis","Hohenlohekreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Holzminden-Kreis","Holzminden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Höxter-Kreis","Höxter")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Hoyerswerda","Bautzen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ilm-Kreis","Ilm-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ingolstadt","Ingolstadt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Jena","Jena")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Jerichower-Land-Kreis","Jerichower Land")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kaiserslautern-Kreis","Kaiserslautern")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kaiserslautern","Kaiserslautern")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Karlsruhe-Kreis","Karlsruhe")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Karlsruhe","Karlsruhe")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kassel-Kreis","Kassel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kassel","Kassel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kaufbeuren","Kaufbeuren")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kelheim-Kreis","Kelheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kempten-Allgäu","Kempten (Allgäu)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kiel","Kiel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kitzingen-Kreis","Kitzingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kleve-Kreis","Kleve")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Koblenz","Koblenz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Köln","Köln")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Konstanz-Kreis","Konstanz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Krefeld","Krefeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kronach-Kreis","Kronach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kulmbach-Kreis","Kulmbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kusel-Kreis","Kusel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Kyffhäuserkreis","Kyffhäuserkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lahn-Dill-Kreis","Lahn-Dill-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Landau-in-der-Pfalz","Landau in der Pfalz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Landsberg-am-Lech-Kreis","Landsberg am Lech")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Landshut-Kreis","Landshut")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Landshut","Landshut")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Leer-Kreis","Leer")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Leipzig-Kreis","Leipzig")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Leipzig","Leipzig")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Leverkusen","Leverkusen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lichtenfels-Kreis","Lichtenfels")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Limburg-Weilburg-Kreis","Limburg-Weilburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lindau-Bodensee-Kreis","Lindau (Bodensee)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lippe-Kreis","Lippe")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lörrach-Kreis","Lörrach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lübeck","Lübeck")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lüchow-Dannenberg-Kreis","Lüchow-Dannenberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ludwigsburg-Kreis","Ludwigsburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ludwigshafen-am-Rhein","Ludwigshafen am Rhein")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ludwigslust-Kreis","Ludwigslust-Parchim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Lüneburg-Kreis","Lüneburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Magdeburg","Magdeburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Main-Kinzig-Kreis","Main-Kinzig-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Main-Spessart-Kreis","Main-Spessart")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Main-Tauber-Kreis","Main-Tauber-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Main-Taunus-Kreis","Main-Taunus-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mainz-Bingen-Kreis","Mainz-Bingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mainz","Mainz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mannheim","Mannheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mansfeld-Südharz-Kreis","Mansfeld-Südharz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Marburg-Biedenkopf-Kreis","Marburg-Biedenkopf")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Märkisch-Oderland-Kreis","Märkisch-Oderland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Märkischer-Kreis","Märkischer Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mayen-Koblenz-Kreis","Mayen-Koblenz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mecklenburg-Strelitz-Kreis","Mecklenburgische Seenplatte")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Meißen-Kreis","Meißen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Memmingen","Memmingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Merzig-Wadern-Kreis","Merzig-Wadern")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mettmann-Kreis","Mettmann")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Miesbach-Kreis","Miesbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Miltenberg-Kreis","Miltenberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Minden-Lübbecke-Kreis","Minden-Lübbecke")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mittelsachsen-Kreis","Mittelsachsen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mönchengladbach","Mönchengladbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mühldorf-am-Inn-Kreis","Mühldorf a. Inn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Mülheim-an-der-Ruhr","Mülheim an der Ruhr")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"München-Kreis","München")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"München","München")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Münster","Münster")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Müritz-Kreis","Mecklenburgische Seenplatte")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neckar-Odenwald-Kreis","Neckar-Odenwald-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neu-Ulm-Kreis","Neu-Ulm")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neubrandenburg","Mecklenburgische Seenplatte")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neuburg-Schrobenhausen-Kreis","Neuburg-Schrobenhausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neumarkt-in-der-Oberpfalz-Kreis","Neumarkt i.d. OPf.")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neumünster","Neumünster")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neunkirchen-Kreis","Neunkirchen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neuss-Rhein-Kreis","Rhein-Kreis Neuss")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neustadt-a.d.-Aisch-Bad-Windsheim-Kreis","Neustadt a.d. Aisch-Bad Windsheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neustadt-a.d.-Waldnaab-Kreis","Neustadt a.d. Waldnaab")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neustadt-an-der-Weinstraße","Neustadt an der Weinstraße")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Neuwied-Kreis","Neuwied")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nienburg-Weser-Kreis","Nienburg (Weser)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nordfriesland-Kreis","Nordfriesland")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nordhausen-Kreis","Nordhausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nordsachsen-Kreis","Nordsachsen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nordvorpommern-Kreis","Vorpommern-Rügen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nordwestmecklenburg-Kreis","Nordwestmecklenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Northeim-Kreis","Northeim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nürnberger-Land-Kreis","Nürnberger Land")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Nürnberg","Nürnberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oberallgäu-Kreis","Oberallgäu")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oberbergischer-Kreis","Oberbergischer Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oberhausen","Oberhausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oberhavel-Kreis","Oberhavel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oberspreewald-Lausitz-Kreis","Oberspreewald-Lausitz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Odenwaldkreis","Odenwaldkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oder-Spree-Kreis","Oder-Spree")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Offenbach-am-Main","Offenbach am Main")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Offenbach-Kreis","Offenbach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oldenburg-Kreis","Oldenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Oldenburg-Oldenburg","Oldenburg (Oldb)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Olpe-Kreis","Olpe")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ortenaukreis","Ortenaukreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Osnabrück-Kreis","Osnabrück")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Osnabrück","Osnabrück")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ostalbkreis","Ostalbkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ostallgäu-Kreis","Ostallgäu")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Osterholz-Kreis","Osterholz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Osterode-am-Harz-Kreis","Göttingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ostholstein-Kreis","Ostholstein")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ostprignitz-Ruppin-Kreis","Ostprignitz-Ruppin")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ostvorpommern-Kreis","Vorpommern-Greifswald")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Paderborn-Kreis","Paderborn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Parchim-Kreis","Ludwigslust-Parchim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Passau-Kreis","Passau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Passau","Passau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Peine-Kreis","Peine")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Pfaffenhofen-an-der-Ilm-Kreis","Pfaffenhofen a.d. Ilm")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Pforzheim","Pforzheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Pinneberg-Kreis","Pinneberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Pirmasens","Pirmasens")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Plauen","Vogtlandkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Plön-Kreis","Plön")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Potsdam-Mittelmark-Kreis","Potsdam-Mittelmark")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Potsdam","Potsdam")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Prignitz-Kreis","Prignitz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rastatt-Kreis","Rastatt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ravensburg-Kreis","Ravensburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Recklinghausen-Kreis","Recklinghausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Regen-Kreis","Regen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Regensburg-Kreis","Regensburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Regensburg","Regensburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rems-Murr-Kreis","Rems-Murr-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Remscheid","Remscheid")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rendsburg-Eckernförde-Kreis","Rendsburg-Eckernförde")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Reutlingen-Kreis","Reutlingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Erft-Kreis","Rhein-Erft-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Hunsrück-Kreis","Rhein-Hunsrück-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Lahn-Kreis","Rhein-Lahn-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Neckar-Kreis","Rhein-Neckar-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Pfalz-Kreis","Rhein-Pfalz-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhein-Sieg-Kreis","Rhein-Sieg-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rheingau-Taunus-Kreis","Rheingau-Taunus-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rheinisch-Bergischer-Kreis","Rheinisch-Bergischer Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rhön-Grabfeld-Kreis","Rhön-Grabfeld")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rosenheim-Kreis","Rosenheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rosenheim","Rosenheim")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rostock","Rostock")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rotenburg-Wümme-Kreis","Rotenburg (Wümme)")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Roth-Kreis","Roth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rottal-Inn-Kreis","Rottal-Inn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rottweil-Kreis","Rottweil")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Rügen-Kreis","Vorpommern-Rügen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saale-Holzland-Kreis","Saale-Holzland-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saale-Orla-Kreis","Saale-Orla-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saalekreis","Saalekreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saalfeld-Rudolstadt-Kreis","Saalfeld-Rudolstadt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saarlouis-Kreis","Saarlouis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Saarpfalz-Kreis","Saarpfalz-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Sächsische-Schweiz-Osterzgebirge-Kreis","Sächsische Schweiz-Osterzgebirge")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Salzgitter","Salzgitter")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Salzlandkreis","Salzlandkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Sankt-Wendel-Kreis","St. Wendel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schaumburg-Kreis","Schaumburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schleswig-Flensburg-Kreis","Schleswig-Flensburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schmalkalden-Meiningen-Kreis","Schmalkalden-Meiningen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwabach","Schwabach")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwäbisch-Hall-Kreis","Schwäbisch Hall")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwalm-Eder-Kreis","Schwalm-Eder-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwandorf-Kreis","Schwandorf")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwarzwald-Baar-Kreis","Schwarzwald-Baar-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schweinfurt-Kreis","Schweinfurt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schweinfurt","Schweinfurt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Schwerin","Schwerin")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Segeberg-Kreis","Segeberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Siegen-Wittgenstein-Kreis","Siegen-Wittgenstein")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Sigmaringen-Kreis","Sigmaringen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Soest-Kreis","Soest")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Solingen","Solingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Soltau-Fallingbostel-Kreis","Heidekreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Sömmerda-Kreis","Sömmerda")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Sonneberg-Kreis","Sonneberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Speyer","Speyer")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Spree-Neiße-Kreis","Spree-Neiße")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stade-Kreis","Stade")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stadtverband-Saarbrücken-Kreis","Regionalverband Saarbrücken")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Starnberg-Kreis","Starnberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Steinburg-Kreis","Steinburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Steinfurt-Kreis","Steinfurt")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stendal-Kreis","Stendal")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stormarn-Kreis","Stormarn")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stralsund","Vorpommern-Rügen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Straubing-Bogen-Kreis","Straubing-Bogen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Straubing","Straubing")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Stuttgart","Stuttgart")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Südliche-Weinstraße-Kreis","Südliche Weinstraße")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Südwestpfalz-Kreis","Südwestpfalz")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Suhl","Suhl")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Teltow-Fläming-Kreis","Teltow-Fläming")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Tirschenreuth-Kreis","Tirschenreuth")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Traunstein-Kreis","Traunstein")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Trier","Trier")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Trier-Saarburg-Kreis","Trier-Saarburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Tübingen-Kreis","Tübingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Tuttlingen-Kreis","Tuttlingen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Uckermark-Kreis","Uckermark")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Uecker-Randow-Kreis","Vorpommern-Greifswald")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Uelzen-Kreis","Uelzen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Ulm","Ulm")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Unna-Kreis","Unna")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Unstrut-Hainich-Kreis","Unstrut-Hainich-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Unterallgäu-Kreis","Unterallgäu")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Vechta-Kreis","Vechta")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Verden-Kreis","Verden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Viersen-Kreis","Viersen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Vogelsbergkreis","Vogelsbergkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Vogtlandkreis","Vogtlandkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Vulkaneifel-Kreis","Vulkaneifel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Waldeck-Frankenberg-Kreis","Waldeck-Frankenberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Waldshut-Kreis","Waldshut")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Warendorf-Kreis","Warendorf")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wartburgkreis","Wartburgkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Weiden-in-der-Oberpfalz","Weiden i.d. OPf.")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Weilheim-Schongau-Kreis","Weilheim-Schongau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Weimarer-Land-Kreis","Weimarer Land")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Weimar","Weimar")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Weißenburg-Gunzenhausen-Kreis","Weißenburg-Gunzenhausen")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Werra-Meißner-Kreis","Werra-Meißner-Kreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wesel-Kreis","Wesel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wesermarsch-Kreis","Wesermarsch")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Westerwaldkreis","Westerwaldkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wetteraukreis","Wetteraukreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wiesbaden","Wiesbaden")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wilhelmshaven","Wilhelmshaven")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wismar","Nordwestmecklenburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wittenberg-Kreis","Wittenberg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wittmund-Kreis","Wittmund")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wolfenbüttel-Kreis","Wolfenbüttel")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wolfsburg","Wolfsburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Worms","Worms")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wunsiedel-im-Fichtelgebirge-Kreis","Wunsiedel i. Fichtelgebirge")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Wuppertal","Wuppertal")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Würzburg-Kreis","Würzburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Würzburg","Würzburg")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Zollernalbkreis","Zollernalbkreis")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Zweibrücken","Zweibrücken")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Zwickau-Kreis","Zwickau")
df_clean_11$regio2 <- str_replace_all(df_clean_11$regio2,"Zwickau","Zwickau")

# Endgueltiger Datensatz
df_immo_cleaned <- df_clean_11

#clean data
rm(list = c("df_clean_1","df_clean_2","df_clean_3","df_clean_4","df_clean_5","df_clean_6","df_clean_7","df_clean_8","df_clean_9", "df_clean_10","df_clean_11",
            "df_clean_na","df_clean_cols"))


# Finales Dataset speichern
write.csv2(df_immo_cleaned, file = "GER/immo_scout_cleaned_final.csv", row.names = FALSE)
write.csv2(df_immo_cleaned, file = "data/immo_scout_cleaned_final.csv", row.names = FALSE)

## -------------------------------------------------------------------------------------------------------------------------------------------------
## Prepare geodata

filePath <- paste0(getwd(),"/GER/geodata/vg2500")
gerKrsMap <- readOGR(dsn=filePath, layer="vg2500_krs")
gerLanMap <- readOGR(dsn=filePath, layer="vg2500_lan")

gerKrsWithId <- data.frame(c(seq(0,400)),gerKrsMap@data[["GEN"]])
gerLanWithId <- data.frame(c(seq(0,15)),gerLanMap@data[["GEN"]])

names(gerKrsWithId) <- c("id", "landkreis")
names(gerLanWithId) <- c("id", "bundesland")

dfLandkreis <- merge(x=tidy(gerKrsMap), y=gerKrsWithId, by="id")
dfBundesland <- merge(x=tidy(gerLanMap), y=gerLanWithId, by="id")

write.csv2(dfLandkreis, file = "GER/geo_landkreis.csv", row.names = FALSE)
write.csv2(dfBundesland, file = "GER/geo_bundesland.csv", row.names = FALSE)

rm(list = c("filePath", "gerKrsMap","gerLanMap","gerKrsWithId","gerLanWithId"))#,"dfLandkreis","dfBundesland"))
